# Generated by Django 4.2.4 on 2023-09-04 21:32

import config.client.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firstname', models.CharField(help_text='First name', max_length=200)),
                ('lastname', models.CharField(help_text='Last name', max_length=200)),
                ('company_name', models.CharField(help_text='Company name', max_length=200)),
                ('inn', models.CharField(help_text='Inn', max_length=200)),
                ('email', models.EmailField(blank=True, max_length=250, null=True, unique=True, verbose_name='email')),
                ('address', models.CharField(help_text='Address', max_length=250)),
                ('location', models.JSONField(default=config.client.models.default_location)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
