# Generated by Django 4.2.4 on 2023-09-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='location_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
