# Generated by Django 4.2.4 on 2023-11-21 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_location_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
    ]
