# Generated by Django 4.2.4 on 2023-10-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_price_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='signature',
            field=models.URLField(blank=True, null=True),
        ),
    ]
