# Generated by Django 4.2.4 on 2023-10-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_order_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='signature',
            field=models.URLField(blank=True, max_length=10000, null=True),
        ),
    ]
