# Generated by Django 4.2.4 on 2023-10-11 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_order_signature'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderSatus',
            new_name='OrderStatus',
        ),
    ]
