# Generated by Django 4.2.4 on 2023-11-20 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0018_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zav_sklad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_zav_sklad', to=settings.AUTH_USER_MODEL),
        ),
    ]
