# Generated by Django 4.2.4 on 2023-11-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_order_zav_sklad'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qqs',
            field=models.BooleanField(default=False),
        ),
    ]
