# Generated by Django 4.2.4 on 2023-11-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_order_qqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qqs_price',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
