# Generated by Django 4.2.4 on 2023-09-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleaccess',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=355, null=True, unique=True),
        ),
    ]
