# Generated by Django 4.2.4 on 2023-09-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_roleaccess_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleaccess',
            name='slug',
        ),
        migrations.AddField(
            model_name='role',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=355, null=True, unique=True),
        ),
    ]
