# Generated by Django 4.2.4 on 2023-09-25 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_role_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.CharField(blank=True, max_length=100, null=True)),
                ('inn', models.CharField(blank=True, max_length=100, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('is_merried', models.IntegerField(choices=[(1, 'Not Merried'), (2, 'Merried'), (3, 'Divorced')], default=1)),
                ('dad_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dad_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('mom_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mom_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
