# Generated by Django 4.2.4 on 2023-10-16 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_agentplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentplan',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_plan', to=settings.AUTH_USER_MODEL),
        ),
    ]
