# Generated by Django 4.2.4 on 2023-11-21 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_agentbalancetoday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
