# Generated by Django 4.2.5 on 2023-09-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_type_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
