# Generated by Django 4.2.5 on 2023-09-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productionproductstockitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionproduct',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
