# Generated by Django 4.2.5 on 2023-10-08 05:02

import config.products.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_productionproduct_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionproduct',
            name='price',
            field=models.JSONField(blank=True, default=config.products.models.default_price, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='amount',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='defect',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='QuantityChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_type', models.CharField(choices=[('add', 'Add'), ('subtract', 'Subtract')], max_length=10)),
                ('type', models.CharField(choices=[('amount', 'Amount'), ('defect', 'Defect')], max_length=10)),
                ('quantity_changed', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
