# Generated by Django 4.2.5 on 2023-10-31 10:39

import config.products.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_products_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionproduct',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='productionproduct',
            name='price',
        ),
        migrations.AddField(
            model_name='productionproductinfo',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.currency'),
        ),
        migrations.AddField(
            model_name='productionproductinfo',
            name='price',
            field=models.JSONField(blank=True, default=config.products.models.default_price, null=True),
        ),
    ]
