# Generated by Django 4.2.4 on 2023-11-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_productionproduct_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='amount_m',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
