# Generated by Django 4.2.4 on 2023-11-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_products_amount_m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='amount_m',
        ),
        migrations.AddField(
            model_name='products',
            name='norm',
            field=models.BigIntegerField(blank=True, default=0, help_text='Norma Product', null=True),
        ),
    ]
