# Generated by Django 4.2.4 on 2023-11-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_products_amount_m_products_norm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='norm',
        ),
        migrations.AddField(
            model_name='productionproductinfo',
            name='norm',
            field=models.BigIntegerField(blank=True, default=0, help_text='Norma Product', null=True),
        ),
    ]
