# Generated by Django 4.2.4 on 2023-11-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_productionproduct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionproduct',
            name='amount_m',
            field=models.BigIntegerField(default=0),
        ),
    ]
