# Generated by Django 4.2.4 on 2023-11-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_productionproduct_amount_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionproduct',
            name='one_m',
            field=models.BigIntegerField(default=0),
        ),
    ]
