# Generated by Django 4.2.4 on 2023-11-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_productionproduct_one_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionproduct',
            name='amount_old',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quantitychange',
            name='change_type',
            field=models.CharField(choices=[('add', 'Add'), ('subtract', 'Вычесть')], max_length=10),
        ),
        migrations.AlterField(
            model_name='quantitychange',
            name='type',
            field=models.CharField(choices=[('amount', 'Количество'), ('defect', 'Дефект')], max_length=10),
        ),
    ]
